# snakemake file

IMAGES = ["fire_hist", "forest_v_savanna", "forest_v_year"]

rule all:
  input:
    '../doc/fire_hist.jpg'

rule download_data:
  output:
    '../Agrofood_co2_emission.csv'
  shell:
    'wget -O {output} "https://docs.google.com/uc?export=download&id=1Wytf3ryf9EtOwaloms8HEzLG0yjtRqxr"'

rule plot_data:
    input:
      '../Agrofood_co2_emission.csv'
    output:
      expand('../doc/{image}.jpg', image=IMAGES)
    shell:
      'python plotting.py'