# snakemake file

rule all:
  input:
    '../doc/fire_hist.jpg'

rule download_data:
  output:
    '../Agrofood_co2_emission.csv'
  shell:
    'wget -O {output} "https://docs.google.com/uc?export=download&id=1Wytf3ryf9EtOwaloms8HEzLG0yjtRqxr"'

rule plot_data:
    input:
      '../Agrofood_co2_emission.csv'
    output:
      exapnd('../doc/fire_hist.jpg', '../doc/forest_v_savanna.jpg', '../doc/forest_v_year.jpg')
    shell:
      'python plotting.py'