name: Unit tests

on:
  push:
    branches:
      - "**" # all branches
  pull_request:
    branches: [ main ] # pull on main

jobs:
  run_style_check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      # - uses: conda-incubator/setup-miniconda@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          activate-environment: env
          environment-file: env.yml
      - run: pycodestyle $(git ls-files "*.py")

  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: conda-incubator/setup-miniconda@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          activate-environment: env
          environment-file: env.yml
      - run: |
          cd test
          python -m unittest test_my_utils.py

  run_func_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: conda-incubator/setup-miniconda@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          activate-environment: env
          environment-file: env.yml
      - run: |
          pip install matplotlib
          cd test
          bash test_print_fires.sh
